name: Build Sphinx Documentation

on:
  push:
    branches: [main] # adjust this to your default branch if different
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.6" # Specify the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U sphinx==7.4.7 sphinx_rtd_theme==2.0.0 myst_parser==3.0.1 sphinxcontrib-napoleon==0.7
          pip freeze | grep sphinx

      - name: Build documentation
        run: |
          cd docs  # adjust this path to where your Sphinx conf.py is located
          sphinx-build -b html . _build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html # adjust this path to your Sphinx output directory
